services:
  ziggymirror:
    build: .
    restart: unless-stopped

    volumes:
      - /srv/volumes/ziggymirror/http:/srv/http

    environment:
      DOWNLOAD_CONCURRENCY: 1

    ports:
      - 8009:80
